name: Update ECR Image

#
on:
  push:
    paths:
      - 'image.tf'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan -target=null_resource.push_django_image -target=null_resource.force_ecs_deployment -out=tfplan
        terraform show -json tfplan | jq -r '(.resource_changes[] | select(.change.actions[] != "no-op") | .address)' > changed_resources.txt

    - name: Check for changes
      id: check_changes
      run: |
        if [ -s changed_resources.txt ]; then
          echo "Changes detected"
          echo "::set-output name=changes::true"
        else
          echo "No changes detected"
          echo "::set-output name=changes::false"
        fi

    - name: Terraform Apply
      if: steps.check_changes.outputs.changes == 'true'
      run: terraform apply -auto-approve -target=null_resource.push_django_image -target=null_resource.force_ecs_deployment
